## NLP Complete Learning

In [1]:
print("hi")

hi

In [1]:
import numpy as np
import sklearn
import pandas as pd

In [9]:
df=pd.read_csv("Urban Air Quality and Health Impact Dataset.csv")
df2=pd.read_csv('Sheet_1.csv')
df2

,response_id,class,response_text,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,response_1,not_flagged,I try and avoid this sort of conflict,NaN,NaN,NaN,NaN,NaN
1,response_2,flagged,Had a friend open up to me about his mental ad...,NaN,NaN,NaN,NaN,NaN
2,response_3,flagged,I saved a girl from suicide once. She was goin...,NaN,NaN,NaN,NaN,NaN
3,response_4,not_flagged,i cant think of one really...i think i may hav...,NaN,NaN,NaN,NaN,NaN
4,response_5,not_flagged,Only really one friend who doesn't fit into th...,,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
75,response_76,not_flagged,"Now that I've been through it, although i'm no...",NaN,NaN,NaN,NaN,NaN
76,response_77,flagged,when my best friends mom past away from od'ing...,NaN,NaN,NaN,NaN,NaN
77,response_78,not_flagged,As a camp counselor I provide stability in kid...,NaN,NaN,NaN,NaN,NaN
78,response_79,flagged,My now girlfriend used to have serious addicti...,NaN,NaN,NaN,NaN,NaN
79,response_80,not_flagged,The one person I ever talked to it was because...,NaN,NaN,NaN,NaN,NaN

->NLP is used when there are certain features where we can't convert string to numeric by encoding. So to make model understand big texts we use NLP so our text can be feeded into model to make predictions.

## NLP ROADMAP

step 1: TEXT PREPROCESSING 1-> (Tokenization, Lemmatization,Stemming, stopwords)
step 2: TEXT PREPROCESSING 2-> Vectorization (Bag of Words, TF-IDF,unigrams, bigrams)
IN THIS WE ARE CLEANING THE TEXT (cleaning the input)
step 3: TEXT PREPROCESSING 3->Advanced Vectorization (Word2vec, avgword2vec) vectors are used to create meaningfull insigths about the data or text which further can be used in machine learning models